name: Linux Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.18", "1.19", "1.20"]
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build test binary
        run: go test -c -race

      # These tests run on Linux only. Apply capabilities and verify we can
      # actually use real AF_PACKET sockets.
      - name: Apply CAP_NET_RAW
        run: sudo setcap cap_net_raw+ep ./packet.test

      - name: Run tests with capabilities
        run: ./packet.test -test.v
