name: Unsupported

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.20"]
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      # Although this package doesn't support Windows, we want to verify that
      # everything builds properly.
      - name: Verify build for non-UNIX platforms
        run: go build
        env:
          GOOS: windows
